services:
  db:
    image: postgres:15
    container_name: dreams_games_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: row_match
    ports:
      - "5432:5432"
    
  redis:
    image: redis:7-alpine
    container_name: dream_games_redis
    ports:
      - "6379:6379"