"""add member_count

Revision ID: cb0ceb0775ef
Revises: 86c38a9c349c
Create Date: 2026-04-05 22:35:39.496144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0ceb0775ef'
down_revision: Union[str, Sequence[str], None] = '86c38a9c349c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('team', sa.Column('member_count', sa.Integer(), nullable=True))
    op.execute("UPDATE team SET member_count = (SELECT COUNT(*) FROM users WHERE users.team_id = team.id)")
    op.alter_column('team', 'member_count', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'member_count')
    # ### end Alembic commands ###
