class BusinessLogicConfig:
    TEAM_CREATION_COST = 1000   
    TEAM_CAPACITY = 20
    TEAM_SUGGESTION_LIMIT = 10
    INITIAL_USER_COINS = 5000
    LEVEL_UP_REWARD = 25
    PASSWORD_MIN_LENGTH = 8
    BCRYPT_ROUNDS = 12
    LEVEL_UP_INCREMENT = 1