from .router_prompt import ROUTER_SYSTEM_PROMPT, ROUTER_USER_TEMPLATE
from .supervisor_prompts import USERS_SUPERVISOR_SYSTEM_PROMPT, TEAMS_SUPERVISOR_SYSTEM_PROMPT
from .responder_prompt import RESPONDER_SYSTEM_PROMPT, RESPONDER_USER_TEMPLATE

__all__ = [
    "ROUTER_SYSTEM_PROMPT",
    "ROUTER_USER_TEMPLATE",
    "USERS_SUPERVISOR_SYSTEM_PROMPT",
    "TEAMS_SUPERVISOR_SYSTEM_PROMPT",
    "RESPONDER_SYSTEM_PROMPT",
    "RESPONDER_USER_TEMPLATE",
]
